"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class imu_data_lcmt(object):

    __slots__ = ["omega", "acc", "temp", "good_packets", "bad_packets", "navQuat", "navOmega", "navRPY"]

    __typenames__ = ["float", "float", "float", "int64_t", "int64_t", "float", "float", "float"]

    __dimensions__ = [[3], [3], None, None, None, [4], [3], [3]]

    def __init__(self):
        self.omega = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.acc = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.temp = 0.0
        """ LCM Type: float """
        self.good_packets = 0
        """ LCM Type: int64_t """
        self.bad_packets = 0
        """ LCM Type: int64_t """
        self.navQuat = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.navOmega = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.navRPY = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(imu_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.omega[:3]))
        buf.write(struct.pack('>3f', *self.acc[:3]))
        buf.write(struct.pack(">fqq", self.temp, self.good_packets, self.bad_packets))
        buf.write(struct.pack('>4f', *self.navQuat[:4]))
        buf.write(struct.pack('>3f', *self.navOmega[:3]))
        buf.write(struct.pack('>3f', *self.navRPY[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != imu_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = imu_data_lcmt()
        self.omega = struct.unpack('>3f', buf.read(12))
        self.acc = struct.unpack('>3f', buf.read(12))
        self.temp, self.good_packets, self.bad_packets = struct.unpack(">fqq", buf.read(20))
        self.navQuat = struct.unpack('>4f', buf.read(16))
        self.navOmega = struct.unpack('>3f', buf.read(12))
        self.navRPY = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if imu_data_lcmt in parents: return 0
        tmphash = (0x491dbdb1d605c43a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if imu_data_lcmt._packed_fingerprint is None:
            imu_data_lcmt._packed_fingerprint = struct.pack(">Q", imu_data_lcmt._get_hash_recursive([]))
        return imu_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", imu_data_lcmt._get_packed_fingerprint())[0]

