"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class arm_cmd_struct(object):

    __slots__ = ["isUsed", "control_mode", "trajectoryLength", "motionType", "jointPosVec", "jointSpeedVec", "jointCurrentVec"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "float", "float", "float"]

    __dimensions__ = [[14], [14], None, None, ["trajectoryLength", 14], ["trajectoryLength", 14], ["trajectoryLength", 14]]

    def __init__(self):
        self.isUsed = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.control_mode = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.trajectoryLength = 0
        """
        control mode for fsm control
        LCM Type: int32_t
        """

        self.motionType = 0
        """
        trajectory length
        LCM Type: int32_t
        """

        self.jointPosVec = []
        """
        motion type
        LCM Type: float[trajectoryLength][14]
        """

        self.jointSpeedVec = []
        """
        trajectory -- joint pos     (14 actuators)
        LCM Type: float[trajectoryLength][14]
        """

        self.jointCurrentVec = []
        """
        trajectory -- joint speed   (14 actuators)
        LCM Type: float[trajectoryLength][14]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(arm_cmd_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>14i', *self.isUsed[:14]))
        buf.write(struct.pack('>14i', *self.control_mode[:14]))
        buf.write(struct.pack(">ii", self.trajectoryLength, self.motionType))
        for i0 in range(self.trajectoryLength):
            buf.write(struct.pack('>14f', *self.jointPosVec[i0][:14]))
        for i0 in range(self.trajectoryLength):
            buf.write(struct.pack('>14f', *self.jointSpeedVec[i0][:14]))
        for i0 in range(self.trajectoryLength):
            buf.write(struct.pack('>14f', *self.jointCurrentVec[i0][:14]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_cmd_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_cmd_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_cmd_struct()
        self.isUsed = struct.unpack('>14i', buf.read(56))
        self.control_mode = struct.unpack('>14i', buf.read(56))
        self.trajectoryLength, self.motionType = struct.unpack(">ii", buf.read(8))
        self.jointPosVec = []
        for i0 in range(self.trajectoryLength):
            self.jointPosVec.append(struct.unpack('>14f', buf.read(56)))
        self.jointSpeedVec = []
        for i0 in range(self.trajectoryLength):
            self.jointSpeedVec.append(struct.unpack('>14f', buf.read(56)))
        self.jointCurrentVec = []
        for i0 in range(self.trajectoryLength):
            self.jointCurrentVec.append(struct.unpack('>14f', buf.read(56)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_cmd_struct in parents: return 0
        tmphash = (0xa0c88537500170a3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_cmd_struct._packed_fingerprint is None:
            arm_cmd_struct._packed_fingerprint = struct.pack(">Q", arm_cmd_struct._get_hash_recursive([]))
        return arm_cmd_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_cmd_struct._get_packed_fingerprint())[0]

