"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class arm_and_hand_cmd_package(object):

    __slots__ = ["isUsed", "control_mode", "jointPosVec", "jointSpeedVec", "jointCurrentVec", "isNewImpedance", "jointStiffness", "handForceMaxValue"]

    __typenames__ = ["int32_t", "int32_t", "float", "float", "float", "int32_t", "float", "float"]

    __dimensions__ = [None, [26], [26], [26], [26], [4], [26], [12]]

    def __init__(self):
        self.isUsed = 0
        """ LCM Type: int32_t """
        self.control_mode = [ 0 for dim0 in range(26) ]
        """ LCM Type: int32_t[26] """
        self.jointPosVec = [ 0.0 for dim0 in range(26) ]
        """
        control mode for fsm control
        LCM Type: float[26]
        """

        self.jointSpeedVec = [ 0.0 for dim0 in range(26) ]
        """
        -- joint pos     (14 left right actuators + 12  left right finger)
        LCM Type: float[26]
        """

        self.jointCurrentVec = [ 0.0 for dim0 in range(26) ]
        """
        -- joint speed   (14 left right actuators + 12  left right finger)
        LCM Type: float[26]
        """

        self.isNewImpedance = [ 0 for dim0 in range(4) ]
        """
        -- joint current/force max value (14 left right actuators + 12  left right finger )
        LCM Type: int32_t[4]
        """

        self.jointStiffness = [ 0.0 for dim0 in range(26) ]
        """
        -- If you want to set stiffness and damping, set this value to 1 (2 left right arms + 2 left right hands)
        LCM Type: float[26]
        """

        self.handForceMaxValue = [ 0.0 for dim0 in range(12) ]
        """
        -- joint stiffness (14 left right actuators + 12  left right finger)
        LCM Type: float[12]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(arm_and_hand_cmd_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.isUsed))
        buf.write(struct.pack('>26i', *self.control_mode[:26]))
        buf.write(struct.pack('>26f', *self.jointPosVec[:26]))
        buf.write(struct.pack('>26f', *self.jointSpeedVec[:26]))
        buf.write(struct.pack('>26f', *self.jointCurrentVec[:26]))
        buf.write(struct.pack('>4i', *self.isNewImpedance[:4]))
        buf.write(struct.pack('>26f', *self.jointStiffness[:26]))
        buf.write(struct.pack('>12f', *self.handForceMaxValue[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_and_hand_cmd_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_and_hand_cmd_package._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_and_hand_cmd_package()
        self.isUsed = struct.unpack(">i", buf.read(4))[0]
        self.control_mode = struct.unpack('>26i', buf.read(104))
        self.jointPosVec = struct.unpack('>26f', buf.read(104))
        self.jointSpeedVec = struct.unpack('>26f', buf.read(104))
        self.jointCurrentVec = struct.unpack('>26f', buf.read(104))
        self.isNewImpedance = struct.unpack('>4i', buf.read(16))
        self.jointStiffness = struct.unpack('>26f', buf.read(104))
        self.handForceMaxValue = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_and_hand_cmd_package in parents: return 0
        tmphash = (0xdd06090007d200ef) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_and_hand_cmd_package._packed_fingerprint is None:
            arm_and_hand_cmd_package._packed_fingerprint = struct.pack(">Q", arm_and_hand_cmd_package._get_hash_recursive([]))
        return arm_and_hand_cmd_package._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_and_hand_cmd_package._get_packed_fingerprint())[0]

