"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class arm_planning_status_struct(object):

    __slots__ = ["current_status", "current_err_code"]

    __typenames__ = ["int32_t", "int32_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.current_status = 0
        """ LCM Type: int32_t """
        self.current_err_code = 0
        """
        current_status: (0 : IDLE ; 1 : SUCCESS ; 2 : FAILED ; 3 : RUNNING)
        LCM Type: int32_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(arm_planning_status_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.current_status, self.current_err_code))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_planning_status_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_planning_status_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_planning_status_struct()
        self.current_status, self.current_err_code = struct.unpack(">ii", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_planning_status_struct in parents: return 0
        tmphash = (0x3e8bf38507028158) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_planning_status_struct._packed_fingerprint is None:
            arm_planning_status_struct._packed_fingerprint = struct.pack(">Q", arm_planning_status_struct._get_hash_recursive([]))
        return arm_planning_status_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_planning_status_struct._get_packed_fingerprint())[0]

