"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class camera_control_command_struct(object):

    __slots__ = ["control_mode"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.control_mode = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(camera_control_command_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.control_mode))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_control_command_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_control_command_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = camera_control_command_struct()
        self.control_mode = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if camera_control_command_struct in parents: return 0
        tmphash = (0xced89b64311db860) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if camera_control_command_struct._packed_fingerprint is None:
            camera_control_command_struct._packed_fingerprint = struct.pack(">Q", camera_control_command_struct._get_hash_recursive([]))
        return camera_control_command_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", camera_control_command_struct._get_packed_fingerprint())[0]

