"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class can_debug_cmd_lcmt(object):

    __slots__ = ["raw_target_position", "raw_target_vel", "raw_target_current", "adrc_x1", "cmd_id", "motor_tarPos", "joint_tarPos"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "int32_t", "float", "float"]

    __dimensions__ = [[14], [14], [14], [14], [14], [14], [14]]

    def __init__(self):
        self.raw_target_position = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.raw_target_vel = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.raw_target_current = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.adrc_x1 = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.cmd_id = [ 0 for dim0 in range(14) ]
        """ LCM Type: int32_t[14] """
        self.motor_tarPos = [ 0.0 for dim0 in range(14) ]
        """ LCM Type: float[14] """
        self.joint_tarPos = [ 0.0 for dim0 in range(14) ]
        """ LCM Type: float[14] """

    def encode(self):
        buf = BytesIO()
        buf.write(can_debug_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>14i', *self.raw_target_position[:14]))
        buf.write(struct.pack('>14i', *self.raw_target_vel[:14]))
        buf.write(struct.pack('>14i', *self.raw_target_current[:14]))
        buf.write(struct.pack('>14i', *self.adrc_x1[:14]))
        buf.write(struct.pack('>14i', *self.cmd_id[:14]))
        buf.write(struct.pack('>14f', *self.motor_tarPos[:14]))
        buf.write(struct.pack('>14f', *self.joint_tarPos[:14]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != can_debug_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return can_debug_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = can_debug_cmd_lcmt()
        self.raw_target_position = struct.unpack('>14i', buf.read(56))
        self.raw_target_vel = struct.unpack('>14i', buf.read(56))
        self.raw_target_current = struct.unpack('>14i', buf.read(56))
        self.adrc_x1 = struct.unpack('>14i', buf.read(56))
        self.cmd_id = struct.unpack('>14i', buf.read(56))
        self.motor_tarPos = struct.unpack('>14f', buf.read(56))
        self.joint_tarPos = struct.unpack('>14f', buf.read(56))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if can_debug_cmd_lcmt in parents: return 0
        tmphash = (0xcaf4c86f831494a4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if can_debug_cmd_lcmt._packed_fingerprint is None:
            can_debug_cmd_lcmt._packed_fingerprint = struct.pack(">Q", can_debug_cmd_lcmt._get_hash_recursive([]))
        return can_debug_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", can_debug_cmd_lcmt._get_packed_fingerprint())[0]

