"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class control_parameter_respones_lcmt(object):

    __slots__ = ["name", "requestNumber", "value", "parameterKind", "requestKind"]

    __typenames__ = ["int8_t", "int64_t", "int8_t", "int8_t", "int8_t"]

    __dimensions__ = [[112], None, [112], None, None]

    def __init__(self):
        self.name = [ 0 for dim0 in range(112) ]
        """ LCM Type: int8_t[112] """
        self.requestNumber = 0
        """ LCM Type: int64_t """
        self.value = [ 0 for dim0 in range(112) ]
        """ LCM Type: int8_t[112] """
        self.parameterKind = 0
        """
        note: maximum size currently 64 bytes
        LCM Type: int8_t
        """

        self.requestKind = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(control_parameter_respones_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>112b', *self.name[:112]))
        buf.write(struct.pack(">q", self.requestNumber))
        buf.write(struct.pack('>112b', *self.value[:112]))
        buf.write(struct.pack(">bb", self.parameterKind, self.requestKind))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_parameter_respones_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_parameter_respones_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = control_parameter_respones_lcmt()
        self.name = struct.unpack('>112b', buf.read(112))
        self.requestNumber = struct.unpack(">q", buf.read(8))[0]
        self.value = struct.unpack('>112b', buf.read(112))
        self.parameterKind, self.requestKind = struct.unpack(">bb", buf.read(2))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if control_parameter_respones_lcmt in parents: return 0
        tmphash = (0x94074e7185765219) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if control_parameter_respones_lcmt._packed_fingerprint is None:
            control_parameter_respones_lcmt._packed_fingerprint = struct.pack(">Q", control_parameter_respones_lcmt._get_hash_recursive([]))
        return control_parameter_respones_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", control_parameter_respones_lcmt._get_packed_fingerprint())[0]

