"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class dcm_gait_planner_lcmt(object):

    __slots__ = ["contact_state"]

    __typenames__ = ["float"]

    __dimensions__ = [[2]]

    def __init__(self):
        self.contact_state = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """

    def encode(self):
        buf = BytesIO()
        buf.write(dcm_gait_planner_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2f', *self.contact_state[:2]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dcm_gait_planner_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dcm_gait_planner_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = dcm_gait_planner_lcmt()
        self.contact_state = struct.unpack('>2f', buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if dcm_gait_planner_lcmt in parents: return 0
        tmphash = (0x60e407f0b55f34d3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if dcm_gait_planner_lcmt._packed_fingerprint is None:
            dcm_gait_planner_lcmt._packed_fingerprint = struct.pack(">Q", dcm_gait_planner_lcmt._get_hash_recursive([]))
        return dcm_gait_planner_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dcm_gait_planner_lcmt._get_packed_fingerprint())[0]

