"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class dcm_arm_control_lcmt(object):

    __slots__ = ["p_WArmEndL_ref", "p_WArmEndL_act", "p_WArmEndR_ref", "p_WArmEndR_act", "v_WArmEndL_ref", "v_WArmEndL_act", "v_WArmEndR_ref", "v_WArmEndR_act", "rpy_WArmEndL_ref", "rpy_WArmEndL_act", "rpy_WArmEndR_ref", "rpy_WArmEndR_act", "w_WArmEndL_ref", "w_WArmEndL_act", "w_WArmEndR_ref", "w_WArmEndR_act"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3], [3]]

    def __init__(self):
        self.p_WArmEndL_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.p_WArmEndL_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.p_WArmEndR_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.p_WArmEndR_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.v_WArmEndL_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.v_WArmEndL_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.v_WArmEndR_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.v_WArmEndR_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy_WArmEndL_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy_WArmEndL_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy_WArmEndR_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy_WArmEndR_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.w_WArmEndL_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.w_WArmEndL_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.w_WArmEndR_ref = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.w_WArmEndR_act = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(dcm_arm_control_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.p_WArmEndL_ref[:3]))
        buf.write(struct.pack('>3f', *self.p_WArmEndL_act[:3]))
        buf.write(struct.pack('>3f', *self.p_WArmEndR_ref[:3]))
        buf.write(struct.pack('>3f', *self.p_WArmEndR_act[:3]))
        buf.write(struct.pack('>3f', *self.v_WArmEndL_ref[:3]))
        buf.write(struct.pack('>3f', *self.v_WArmEndL_act[:3]))
        buf.write(struct.pack('>3f', *self.v_WArmEndR_ref[:3]))
        buf.write(struct.pack('>3f', *self.v_WArmEndR_act[:3]))
        buf.write(struct.pack('>3f', *self.rpy_WArmEndL_ref[:3]))
        buf.write(struct.pack('>3f', *self.rpy_WArmEndL_act[:3]))
        buf.write(struct.pack('>3f', *self.rpy_WArmEndR_ref[:3]))
        buf.write(struct.pack('>3f', *self.rpy_WArmEndR_act[:3]))
        buf.write(struct.pack('>3f', *self.w_WArmEndL_ref[:3]))
        buf.write(struct.pack('>3f', *self.w_WArmEndL_act[:3]))
        buf.write(struct.pack('>3f', *self.w_WArmEndR_ref[:3]))
        buf.write(struct.pack('>3f', *self.w_WArmEndR_act[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dcm_arm_control_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dcm_arm_control_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = dcm_arm_control_lcmt()
        self.p_WArmEndL_ref = struct.unpack('>3f', buf.read(12))
        self.p_WArmEndL_act = struct.unpack('>3f', buf.read(12))
        self.p_WArmEndR_ref = struct.unpack('>3f', buf.read(12))
        self.p_WArmEndR_act = struct.unpack('>3f', buf.read(12))
        self.v_WArmEndL_ref = struct.unpack('>3f', buf.read(12))
        self.v_WArmEndL_act = struct.unpack('>3f', buf.read(12))
        self.v_WArmEndR_ref = struct.unpack('>3f', buf.read(12))
        self.v_WArmEndR_act = struct.unpack('>3f', buf.read(12))
        self.rpy_WArmEndL_ref = struct.unpack('>3f', buf.read(12))
        self.rpy_WArmEndL_act = struct.unpack('>3f', buf.read(12))
        self.rpy_WArmEndR_ref = struct.unpack('>3f', buf.read(12))
        self.rpy_WArmEndR_act = struct.unpack('>3f', buf.read(12))
        self.w_WArmEndL_ref = struct.unpack('>3f', buf.read(12))
        self.w_WArmEndL_act = struct.unpack('>3f', buf.read(12))
        self.w_WArmEndR_ref = struct.unpack('>3f', buf.read(12))
        self.w_WArmEndR_act = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if dcm_arm_control_lcmt in parents: return 0
        tmphash = (0x318414332ce70483) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if dcm_arm_control_lcmt._packed_fingerprint is None:
            dcm_arm_control_lcmt._packed_fingerprint = struct.pack(">Q", dcm_arm_control_lcmt._get_hash_recursive([]))
        return dcm_arm_control_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", dcm_arm_control_lcmt._get_packed_fingerprint())[0]

