"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class doll_motor_debug_data_struct(object):

    __slots__ = ["n_dof", "motor_pos_now", "motor_vel_now", "motor_current_now", "joint_pos_now", "joint_vel_now", "joint_current_now"]

    __typenames__ = ["int32_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, ["n_dof"], ["n_dof"], ["n_dof"], ["n_dof"], ["n_dof"], ["n_dof"]]

    def __init__(self):
        self.n_dof = 0
        """ LCM Type: int32_t """
        self.motor_pos_now = []
        """
        number of degrees
        LCM Type: float[n_dof]
        """

        self.motor_vel_now = []
        """ LCM Type: float[n_dof] """
        self.motor_current_now = []
        """ LCM Type: float[n_dof] """
        self.joint_pos_now = []
        """ LCM Type: float[n_dof] """
        self.joint_vel_now = []
        """ LCM Type: float[n_dof] """
        self.joint_current_now = []
        """ LCM Type: float[n_dof] """

    def encode(self):
        buf = BytesIO()
        buf.write(doll_motor_debug_data_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.n_dof))
        buf.write(struct.pack('>%df' % self.n_dof, *self.motor_pos_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.motor_vel_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.motor_current_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.joint_pos_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.joint_vel_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.joint_current_now[:self.n_dof]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != doll_motor_debug_data_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return doll_motor_debug_data_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = doll_motor_debug_data_struct()
        self.n_dof = struct.unpack(">i", buf.read(4))[0]
        self.motor_pos_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.motor_vel_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.motor_current_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.joint_pos_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.joint_vel_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.joint_current_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if doll_motor_debug_data_struct in parents: return 0
        tmphash = (0x21b8aa3924e89513) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if doll_motor_debug_data_struct._packed_fingerprint is None:
            doll_motor_debug_data_struct._packed_fingerprint = struct.pack(">Q", doll_motor_debug_data_struct._get_hash_recursive([]))
        return doll_motor_debug_data_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", doll_motor_debug_data_struct._get_packed_fingerprint())[0]

