"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ecat_zeroerr_debug_data_lcmt(object):

    __slots__ = ["ctrlWord", "original_tarPos", "mc_tarPos", "mc_curPos", "original_curPos"]

    __typenames__ = ["int16_t", "float", "float", "float", "float"]

    __dimensions__ = [[2], [2], [2], [2], [2]]

    def __init__(self):
        self.ctrlWord = [ 0 for dim0 in range(2) ]
        """ LCM Type: int16_t[2] """
        self.original_tarPos = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """
        self.mc_tarPos = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """
        self.mc_curPos = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """
        self.original_curPos = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """

    def encode(self):
        buf = BytesIO()
        buf.write(ecat_zeroerr_debug_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2h', *self.ctrlWord[:2]))
        buf.write(struct.pack('>2f', *self.original_tarPos[:2]))
        buf.write(struct.pack('>2f', *self.mc_tarPos[:2]))
        buf.write(struct.pack('>2f', *self.mc_curPos[:2]))
        buf.write(struct.pack('>2f', *self.original_curPos[:2]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ecat_zeroerr_debug_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ecat_zeroerr_debug_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ecat_zeroerr_debug_data_lcmt()
        self.ctrlWord = struct.unpack('>2h', buf.read(4))
        self.original_tarPos = struct.unpack('>2f', buf.read(8))
        self.mc_tarPos = struct.unpack('>2f', buf.read(8))
        self.mc_curPos = struct.unpack('>2f', buf.read(8))
        self.original_curPos = struct.unpack('>2f', buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ecat_zeroerr_debug_data_lcmt in parents: return 0
        tmphash = (0x22de83415c820907) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ecat_zeroerr_debug_data_lcmt._packed_fingerprint is None:
            ecat_zeroerr_debug_data_lcmt._packed_fingerprint = struct.pack(">Q", ecat_zeroerr_debug_data_lcmt._get_hash_recursive([]))
        return ecat_zeroerr_debug_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ecat_zeroerr_debug_data_lcmt._get_packed_fingerprint())[0]

