"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hand_sensor_struct(object):
    """
    Unit   N , N*m  , m  , m/s , rad , rad/s , A
    arm_curStatus
    0：停止模式
    1：电流模式
    2：速度模式
    3：位置模式
    arm_curErrCode
    对应位为0表示无错误，为1表示出现错误
    bit0  代表软件错误，如电机运行时写入FLASH等
    bit1  代表过压
    bit2  代表欠压
    bit4  代表启动错误
    bit5  代表速度反馈错误
    bit6  代表过流
    bit16 代表编码器通讯错误
    bit17 代表电机温度过高
    bit18 代表电路板温度过高
    """

    __slots__ = ["isUsed", "curStatusVec", "curErrCodeVec", "curJointPosVec", "curJointSpeedVec", "curForceVec", "current_status", "current_err_code"]

    __typenames__ = ["int32_t", "int8_t", "int8_t", "float", "float", "float", "int32_t", "int32_t"]

    __dimensions__ = [[12], [12], [12], [12], [12], [12], None, None]

    def __init__(self):
        self.isUsed = [ 0 for dim0 in range(12) ]
        """ LCM Type: int32_t[12] """
        self.curStatusVec = [ 0 for dim0 in range(12) ]
        """ LCM Type: int8_t[12] """
        self.curErrCodeVec = [ 0 for dim0 in range(12) ]
        """
        current joint status           (6 actuators)
        LCM Type: int8_t[12]
        """

        self.curJointPosVec = [ 0.0 for dim0 in range(12) ]
        """
        current error code             (6 actuators)
        LCM Type: float[12]
        """

        self.curJointSpeedVec = [ 0.0 for dim0 in range(12) ]
        """
        current joint pos              (6 actuators)
        LCM Type: float[12]
        """

        self.curForceVec = [ 0.0 for dim0 in range(12) ]
        """
        current finger joint speed     (6 actuators)
        LCM Type: float[12]
        """

        self.current_status = 0
        """
        current force value            (6 actuators)
        LCM Type: int32_t
        """

        self.current_err_code = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(hand_sensor_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12i', *self.isUsed[:12]))
        buf.write(struct.pack('>12b', *self.curStatusVec[:12]))
        buf.write(struct.pack('>12b', *self.curErrCodeVec[:12]))
        buf.write(struct.pack('>12f', *self.curJointPosVec[:12]))
        buf.write(struct.pack('>12f', *self.curJointSpeedVec[:12]))
        buf.write(struct.pack('>12f', *self.curForceVec[:12]))
        buf.write(struct.pack(">ii", self.current_status, self.current_err_code))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hand_sensor_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hand_sensor_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hand_sensor_struct()
        self.isUsed = struct.unpack('>12i', buf.read(48))
        self.curStatusVec = struct.unpack('>12b', buf.read(12))
        self.curErrCodeVec = struct.unpack('>12b', buf.read(12))
        self.curJointPosVec = struct.unpack('>12f', buf.read(48))
        self.curJointSpeedVec = struct.unpack('>12f', buf.read(48))
        self.curForceVec = struct.unpack('>12f', buf.read(48))
        self.current_status, self.current_err_code = struct.unpack(">ii", buf.read(8))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hand_sensor_struct in parents: return 0
        tmphash = (0x85b29e9ff4c1b70f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hand_sensor_struct._packed_fingerprint is None:
            hand_sensor_struct._packed_fingerprint = struct.pack(">Q", hand_sensor_struct._get_hash_recursive([]))
        return hand_sensor_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hand_sensor_struct._get_packed_fingerprint())[0]

