"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hand_cmd_struct(object):
    """
    Unit   N , N*m  , m  , m/s , rad , rad/s , A
    arm motionType commit
    motionType = 0         disable arm(stop)
    motionType = 1         go home
    motionType = 2         clear error code
    motionType = 3         pos control mode
    motionType = 4         speed control mode
    motionType = 5         current control mode
    """

    __slots__ = ["isUsed", "control_mode", "trajectoryLength", "motionType", "jointPosVec", "jointSpeedVec", "forceMaxValue", "gestureSequence"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "int32_t", "float", "float", "float", "int8_t"]

    __dimensions__ = [[12], None, None, None, [12], [12], [12], None]

    def __init__(self):
        self.isUsed = [ 0 for dim0 in range(12) ]
        """ LCM Type: int32_t[12] """
        self.control_mode = 0
        """ LCM Type: int32_t """
        self.trajectoryLength = 0
        """
        control mode for fsm control
        LCM Type: int32_t
        """

        self.motionType = 0
        """
        trajectory length
        LCM Type: int32_t
        """

        self.jointPosVec = [ 0.0 for dim0 in range(12) ]
        """
        motion type
        LCM Type: float[12]
        """

        self.jointSpeedVec = [ 0.0 for dim0 in range(12) ]
        """
        trajectory -- finger joint pos       (6 actuators)
        LCM Type: float[12]
        """

        self.forceMaxValue = [ 0.0 for dim0 in range(12) ]
        """
        trajectory -- finger joint speed     (6 actuators)
        LCM Type: float[12]
        """

        self.gestureSequence = 0
        """
        force max value                      (8 actuators)
        LCM Type: int8_t
        """


    def encode(self):
        buf = BytesIO()
        buf.write(hand_cmd_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12i', *self.isUsed[:12]))
        buf.write(struct.pack(">iii", self.control_mode, self.trajectoryLength, self.motionType))
        buf.write(struct.pack('>12f', *self.jointPosVec[:12]))
        buf.write(struct.pack('>12f', *self.jointSpeedVec[:12]))
        buf.write(struct.pack('>12f', *self.forceMaxValue[:12]))
        buf.write(struct.pack(">b", self.gestureSequence))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hand_cmd_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hand_cmd_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hand_cmd_struct()
        self.isUsed = struct.unpack('>12i', buf.read(48))
        self.control_mode, self.trajectoryLength, self.motionType = struct.unpack(">iii", buf.read(12))
        self.jointPosVec = struct.unpack('>12f', buf.read(48))
        self.jointSpeedVec = struct.unpack('>12f', buf.read(48))
        self.forceMaxValue = struct.unpack('>12f', buf.read(48))
        self.gestureSequence = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hand_cmd_struct in parents: return 0
        tmphash = (0xa71cf6d7888eeee) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hand_cmd_struct._packed_fingerprint is None:
            hand_cmd_struct._packed_fingerprint = struct.pack(">Q", hand_cmd_struct._get_hash_recursive([]))
        return hand_cmd_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hand_cmd_struct._get_packed_fingerprint())[0]

