"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class hand_debug_cmd_lcmt(object):

    __slots__ = ["joint_tarPos"]

    __typenames__ = ["float"]

    __dimensions__ = [[12]]

    def __init__(self):
        self.joint_tarPos = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(hand_debug_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.joint_tarPos[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != hand_debug_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return hand_debug_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = hand_debug_cmd_lcmt()
        self.joint_tarPos = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if hand_debug_cmd_lcmt in parents: return 0
        tmphash = (0x63efd285cf91949c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if hand_debug_cmd_lcmt._packed_fingerprint is None:
            hand_debug_cmd_lcmt._packed_fingerprint = struct.pack(">Q", hand_debug_cmd_lcmt._get_hash_recursive([]))
        return hand_debug_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", hand_debug_cmd_lcmt._get_packed_fingerprint())[0]

