"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class height_map_lcmt(object):

    __slots__ = ["h"]

    __typenames__ = ["float"]

    __dimensions__ = [[315]]

    def __init__(self):
        self.h = [ 0.0 for dim0 in range(315) ]
        """ LCM Type: float[315] """

    def encode(self):
        buf = BytesIO()
        buf.write(height_map_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>315f', *self.h[:315]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != height_map_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return height_map_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = height_map_lcmt()
        self.h = struct.unpack('>315f', buf.read(1260))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if height_map_lcmt in parents: return 0
        tmphash = (0xf19bfc2ff1ff5284) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if height_map_lcmt._packed_fingerprint is None:
            height_map_lcmt._packed_fingerprint = struct.pack(">Q", height_map_lcmt._get_hash_recursive([]))
        return height_map_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", height_map_lcmt._get_packed_fingerprint())[0]

