"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from joint_cmd_lcmt import joint_cmd_lcmt

class joint_cmds_lcmt(object):

    __slots__ = ["cmds_num", "cmds"]

    __typenames__ = ["int16_t", "joint_cmd_lcmt"]

    __dimensions__ = [None, ["cmds_num"]]

    def __init__(self):
        self.cmds_num = 0
        """ LCM Type: int16_t """
        self.cmds = []
        """ LCM Type: joint_cmd_lcmt[cmds_num] """

    def encode(self):
        buf = BytesIO()
        buf.write(joint_cmds_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.cmds_num))
        for i0 in range(self.cmds_num):
            assert self.cmds[i0]._get_packed_fingerprint() == joint_cmd_lcmt._get_packed_fingerprint()
            self.cmds[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joint_cmds_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joint_cmds_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = joint_cmds_lcmt()
        self.cmds_num = struct.unpack(">h", buf.read(2))[0]
        self.cmds = []
        for i0 in range(self.cmds_num):
            self.cmds.append(joint_cmd_lcmt._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if joint_cmds_lcmt in parents: return 0
        newparents = parents + [joint_cmds_lcmt]
        tmphash = (0xa610e843b9e734ce+ joint_cmd_lcmt._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if joint_cmds_lcmt._packed_fingerprint is None:
            joint_cmds_lcmt._packed_fingerprint = struct.pack(">Q", joint_cmds_lcmt._get_hash_recursive([]))
        return joint_cmds_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", joint_cmds_lcmt._get_packed_fingerprint())[0]

