"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcm_response_lcmt(object):

    __slots__ = ["robot_fsm", "switch_flag"]

    __typenames__ = ["int8_t", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.robot_fsm = 0
        """ LCM Type: int8_t """
        self.switch_flag = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_response_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.robot_fsm, self.switch_flag))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_response_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_response_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcm_response_lcmt()
        self.robot_fsm, self.switch_flag = struct.unpack(">bb", buf.read(2))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcm_response_lcmt in parents: return 0
        tmphash = (0x9d8ec35cb22984ad) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcm_response_lcmt._packed_fingerprint is None:
            lcm_response_lcmt._packed_fingerprint = struct.pack(">Q", lcm_response_lcmt._get_hash_recursive([]))
        return lcm_response_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcm_response_lcmt._get_packed_fingerprint())[0]

