"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class led_controller_lcmt(object):

    __slots__ = ["classes", "control_word", "description"]

    __typenames__ = ["string", "int16_t", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.classes = ""
        """ LCM Type: string """
        self.control_word = 0
        """ LCM Type: int16_t """
        self.description = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(led_controller_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __classes_encoded = self.classes.encode('utf-8')
        buf.write(struct.pack('>I', len(__classes_encoded)+1))
        buf.write(__classes_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">h", self.control_word))
        __description_encoded = self.description.encode('utf-8')
        buf.write(struct.pack('>I', len(__description_encoded)+1))
        buf.write(__description_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != led_controller_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return led_controller_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = led_controller_lcmt()
        __classes_len = struct.unpack('>I', buf.read(4))[0]
        self.classes = buf.read(__classes_len)[:-1].decode('utf-8', 'replace')
        self.control_word = struct.unpack(">h", buf.read(2))[0]
        __description_len = struct.unpack('>I', buf.read(4))[0]
        self.description = buf.read(__description_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if led_controller_lcmt in parents: return 0
        tmphash = (0x4015416908616319) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if led_controller_lcmt._packed_fingerprint is None:
            led_controller_lcmt._packed_fingerprint = struct.pack(">Q", led_controller_lcmt._get_hash_recursive([]))
        return led_controller_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", led_controller_lcmt._get_packed_fingerprint())[0]

