"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Lumos_doll_data_struct(object):

    __slots__ = ["n_dof", "pos_now", "vel_now", "current_now"]

    __typenames__ = ["int32_t", "float", "float", "float"]

    __dimensions__ = [None, ["n_dof"], ["n_dof"], ["n_dof"]]

    def __init__(self):
        self.n_dof = 0
        """ LCM Type: int32_t """
        self.pos_now = []
        """
        number of degrees
        LCM Type: float[n_dof]
        """

        self.vel_now = []
        """ LCM Type: float[n_dof] """
        self.current_now = []
        """ LCM Type: float[n_dof] """

    def encode(self):
        buf = BytesIO()
        buf.write(Lumos_doll_data_struct._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.n_dof))
        buf.write(struct.pack('>%df' % self.n_dof, *self.pos_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.vel_now[:self.n_dof]))
        buf.write(struct.pack('>%df' % self.n_dof, *self.current_now[:self.n_dof]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Lumos_doll_data_struct._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Lumos_doll_data_struct._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Lumos_doll_data_struct()
        self.n_dof = struct.unpack(">i", buf.read(4))[0]
        self.pos_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.vel_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        self.current_now = struct.unpack('>%df' % self.n_dof, buf.read(self.n_dof * 4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Lumos_doll_data_struct in parents: return 0
        tmphash = (0x4874d431ea64c8f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Lumos_doll_data_struct._packed_fingerprint is None:
            Lumos_doll_data_struct._packed_fingerprint = struct.pack(">Q", Lumos_doll_data_struct._get_hash_recursive([]))
        return Lumos_doll_data_struct._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Lumos_doll_data_struct._get_packed_fingerprint())[0]

