"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lumos_lcm_battery(object):

    __slots__ = ["voltage", "current", "percentage"]

    __typenames__ = ["float", "float", "int16_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.voltage = 0.0
        """ LCM Type: float """
        self.current = 0.0
        """ LCM Type: float """
        self.percentage = 0
        """ LCM Type: int16_t """

    def encode(self):
        buf = BytesIO()
        buf.write(lumos_lcm_battery._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffh", self.voltage, self.current, self.percentage))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lumos_lcm_battery._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lumos_lcm_battery._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lumos_lcm_battery()
        self.voltage, self.current, self.percentage = struct.unpack(">ffh", buf.read(10))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lumos_lcm_battery in parents: return 0
        tmphash = (0x60badf70c35a97c7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lumos_lcm_battery._packed_fingerprint is None:
            lumos_lcm_battery._packed_fingerprint = struct.pack(">Q", lumos_lcm_battery._get_hash_recursive([]))
        return lumos_lcm_battery._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lumos_lcm_battery._get_packed_fingerprint())[0]

