"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lumos_lcm_control(object):
    """
    DEPRECATED: use robot_cmd_lcmt instead (topic: lcm_robot_cmd)
    NOTE: robot_cmd_lcmt has int8_t policy_type instead of boolean upstate
    """

    __slots__ = ["state", "x", "y", "yaw", "upstate"]

    __typenames__ = ["int8_t", "float", "float", "float", "boolean"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.state = 0
        """ LCM Type: int8_t """
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """ LCM Type: float """
        self.yaw = 0.0
        """ LCM Type: float """
        self.upstate = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(lumos_lcm_control._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bfffb", self.state, self.x, self.y, self.yaw, self.upstate))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lumos_lcm_control._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lumos_lcm_control._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lumos_lcm_control()
        self.state, self.x, self.y, self.yaw = struct.unpack(">bfff", buf.read(13))
        self.upstate = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lumos_lcm_control in parents: return 0
        tmphash = (0xaac020ff30317c45) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lumos_lcm_control._packed_fingerprint is None:
            lumos_lcm_control._packed_fingerprint = struct.pack(">Q", lumos_lcm_control._get_hash_recursive([]))
        return lumos_lcm_control._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lumos_lcm_control._get_packed_fingerprint())[0]

