"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lumos_lcm_motor(object):
    """ DEPRECATED: motor status/type identification (legacy) """

    __slots__ = ["type", "state", "id"]

    __typenames__ = ["int16_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.type = 0
        """ LCM Type: int16_t """
        self.state = 0
        """ LCM Type: int16_t """
        self.id = 0
        """ LCM Type: int16_t """

    def encode(self):
        buf = BytesIO()
        buf.write(lumos_lcm_motor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhh", self.type, self.state, self.id))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lumos_lcm_motor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lumos_lcm_motor._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lumos_lcm_motor()
        self.type, self.state, self.id = struct.unpack(">hhh", buf.read(6))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lumos_lcm_motor in parents: return 0
        tmphash = (0xa4eddd176427fed2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lumos_lcm_motor._packed_fingerprint is None:
            lumos_lcm_motor._packed_fingerprint = struct.pack(">Q", lumos_lcm_motor._get_hash_recursive([]))
        return lumos_lcm_motor._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lumos_lcm_motor._get_packed_fingerprint())[0]

