"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lumos_lcm_agx(object):
    """ DEPRECATED: use robot_status_lcmt instead (topic: lcm_robot_status) """

    __slots__ = ["state", "type"]

    __typenames__ = ["int8_t", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.state = 0
        """ LCM Type: int8_t """
        self.type = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(lumos_lcm_agx._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.state, self.type))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lumos_lcm_agx._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lumos_lcm_agx._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lumos_lcm_agx()
        self.state, self.type = struct.unpack(">bb", buf.read(2))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lumos_lcm_agx in parents: return 0
        tmphash = (0xb4e1a451bc793e4e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lumos_lcm_agx._packed_fingerprint is None:
            lumos_lcm_agx._packed_fingerprint = struct.pack(">Q", lumos_lcm_agx._get_hash_recursive([]))
        return lumos_lcm_agx._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lumos_lcm_agx._get_packed_fingerprint())[0]

