"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rl_walk_input_ob_lcmt(object):

    __slots__ = ["data"]

    __typenames__ = ["double"]

    __dimensions__ = [[47]]

    def __init__(self):
        self.data = [ 0.0 for dim0 in range(47) ]
        """ LCM Type: double[47] """

    def encode(self):
        buf = BytesIO()
        buf.write(rl_walk_input_ob_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>47d', *self.data[:47]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rl_walk_input_ob_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rl_walk_input_ob_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rl_walk_input_ob_lcmt()
        self.data = struct.unpack('>47d', buf.read(376))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rl_walk_input_ob_lcmt in parents: return 0
        tmphash = (0x2b2f4ef42124f333) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rl_walk_input_ob_lcmt._packed_fingerprint is None:
            rl_walk_input_ob_lcmt._packed_fingerprint = struct.pack(">Q", rl_walk_input_ob_lcmt._get_hash_recursive([]))
        return rl_walk_input_ob_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rl_walk_input_ob_lcmt._get_packed_fingerprint())[0]

