"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_cmd_lcmt(object):

    __slots__ = ["state", "x", "y", "yaw", "policy_type"]

    __typenames__ = ["int8_t", "float", "float", "float", "int8_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.state = 0
        """ LCM Type: int8_t """
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """ LCM Type: float """
        self.yaw = 0.0
        """ LCM Type: float """
        self.policy_type = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_cmd_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bfffb", self.state, self.x, self.y, self.yaw, self.policy_type))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_cmd_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_cmd_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_cmd_lcmt()
        self.state, self.x, self.y, self.yaw, self.policy_type = struct.unpack(">bfffb", buf.read(14))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_cmd_lcmt in parents: return 0
        tmphash = (0xaf3834756bdc0eb6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_cmd_lcmt._packed_fingerprint is None:
            robot_cmd_lcmt._packed_fingerprint = struct.pack(">Q", robot_cmd_lcmt._get_hash_recursive([]))
        return robot_cmd_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_cmd_lcmt._get_packed_fingerprint())[0]

