"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class robot_status_lcmt(object):

    __slots__ = ["state", "type", "audio_file"]

    __typenames__ = ["int8_t", "int8_t", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.state = 0
        """ LCM Type: int8_t """
        self.type = 0
        """ LCM Type: int8_t """
        self.audio_file = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(robot_status_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.state, self.type))
        __audio_file_encoded = self.audio_file.encode('utf-8')
        buf.write(struct.pack('>I', len(__audio_file_encoded)+1))
        buf.write(__audio_file_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_status_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_status_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = robot_status_lcmt()
        self.state, self.type = struct.unpack(">bb", buf.read(2))
        __audio_file_len = struct.unpack('>I', buf.read(4))[0]
        self.audio_file = buf.read(__audio_file_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if robot_status_lcmt in parents: return 0
        tmphash = (0x84c893299c94b619) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if robot_status_lcmt._packed_fingerprint is None:
            robot_status_lcmt._packed_fingerprint = struct.pack(">Q", robot_status_lcmt._get_hash_recursive([]))
        return robot_status_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", robot_status_lcmt._get_packed_fingerprint())[0]

