"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class sdk_lcmt_type(object):

    __slots__ = ["controller_type"]

    __typenames__ = ["int16_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.controller_type = 0
        """ LCM Type: int16_t """

    def encode(self):
        buf = BytesIO()
        buf.write(sdk_lcmt_type._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.controller_type))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sdk_lcmt_type._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sdk_lcmt_type._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sdk_lcmt_type()
        self.controller_type = struct.unpack(">h", buf.read(2))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sdk_lcmt_type in parents: return 0
        tmphash = (0xeeef131a4d304ec6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sdk_lcmt_type._packed_fingerprint is None:
            sdk_lcmt_type._packed_fingerprint = struct.pack(">Q", sdk_lcmt_type._get_hash_recursive([]))
        return sdk_lcmt_type._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sdk_lcmt_type._get_packed_fingerprint())[0]

