"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import sdk_lcmt_joint_cmd

class sdk_lcmt_joint_cmds(object):

    __slots__ = ["cmds_num", "cmds"]

    __typenames__ = ["int16_t", "sdk_lcmt_joint_cmd"]

    __dimensions__ = [None, ["cmds_num"]]

    def __init__(self):
        self.cmds_num = 0
        """ LCM Type: int16_t """
        self.cmds = []
        """ LCM Type: sdk_lcmt_joint_cmd[cmds_num] """

    def encode(self):
        buf = BytesIO()
        buf.write(sdk_lcmt_joint_cmds._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.cmds_num))
        for i0 in range(self.cmds_num):
            assert self.cmds[i0]._get_packed_fingerprint() == sdk_lcmt_joint_cmd._get_packed_fingerprint()
            self.cmds[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sdk_lcmt_joint_cmds._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sdk_lcmt_joint_cmds._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sdk_lcmt_joint_cmds()
        self.cmds_num = struct.unpack(">h", buf.read(2))[0]
        self.cmds = []
        for i0 in range(self.cmds_num):
            self.cmds.append(sdk_lcmt_joint_cmd._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sdk_lcmt_joint_cmds in parents: return 0
        newparents = parents + [sdk_lcmt_joint_cmds]
        tmphash = (0xa610e843b9e734ce+ sdk_lcmt_joint_cmd._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sdk_lcmt_joint_cmds._packed_fingerprint is None:
            sdk_lcmt_joint_cmds._packed_fingerprint = struct.pack(">Q", sdk_lcmt_joint_cmds._get_hash_recursive([]))
        return sdk_lcmt_joint_cmds._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sdk_lcmt_joint_cmds._get_packed_fingerprint())[0]

