"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class sdk_lcmt_joint_cmd(object):

    __slots__ = ["component_type", "joint_id", "ctrlWord", "tarPos", "tarVel", "tarCur", "tarTor", "res1", "res2", "res3", "res4"]

    __typenames__ = ["int16_t", "int16_t", "int16_t", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.component_type = 0
        """ LCM Type: int16_t """
        self.joint_id = 0
        """ LCM Type: int16_t """
        self.ctrlWord = 0
        """ LCM Type: int16_t """
        self.tarPos = 0.0
        """ LCM Type: float """
        self.tarVel = 0.0
        """ LCM Type: float """
        self.tarCur = 0.0
        """ LCM Type: float """
        self.tarTor = 0.0
        """ LCM Type: float """
        self.res1 = 0.0
        """ LCM Type: float """
        self.res2 = 0.0
        """ LCM Type: float """
        self.res3 = 0.0
        """ LCM Type: float """
        self.res4 = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(sdk_lcmt_joint_cmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhhffffffff", self.component_type, self.joint_id, self.ctrlWord, self.tarPos, self.tarVel, self.tarCur, self.tarTor, self.res1, self.res2, self.res3, self.res4))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sdk_lcmt_joint_cmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sdk_lcmt_joint_cmd._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sdk_lcmt_joint_cmd()
        self.component_type, self.joint_id, self.ctrlWord, self.tarPos, self.tarVel, self.tarCur, self.tarTor, self.res1, self.res2, self.res3, self.res4 = struct.unpack(">hhhffffffff", buf.read(38))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sdk_lcmt_joint_cmd in parents: return 0
        tmphash = (0x2172e117ea9be2c5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sdk_lcmt_joint_cmd._packed_fingerprint is None:
            sdk_lcmt_joint_cmd._packed_fingerprint = struct.pack(">Q", sdk_lcmt_joint_cmd._get_hash_recursive([]))
        return sdk_lcmt_joint_cmd._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sdk_lcmt_joint_cmd._get_packed_fingerprint())[0]

