"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class sdk_lcmt_joint_data(object):

    __slots__ = ["component_type", "joint_id", "stat", "pos_high", "num_cycles_high", "pos_low", "num_cycles_low", "vel", "cur", "tor", "res1", "res2", "res3", "res4"]

    __typenames__ = ["int16_t", "int16_t", "int16_t", "float", "int16_t", "float", "int16_t", "float", "float", "float", "int16_t", "int16_t", "int16_t", "int16_t"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.component_type = 0
        """ LCM Type: int16_t """
        self.joint_id = 0
        """ LCM Type: int16_t """
        self.stat = 0
        """ LCM Type: int16_t """
        self.pos_high = 0.0
        """ LCM Type: float """
        self.num_cycles_high = 0
        """ LCM Type: int16_t """
        self.pos_low = 0.0
        """ LCM Type: float """
        self.num_cycles_low = 0
        """ LCM Type: int16_t """
        self.vel = 0.0
        """ LCM Type: float """
        self.cur = 0.0
        """ LCM Type: float """
        self.tor = 0.0
        """ LCM Type: float """
        self.res1 = 0
        """ LCM Type: int16_t """
        self.res2 = 0
        """ LCM Type: int16_t """
        self.res3 = 0
        """ LCM Type: int16_t """
        self.res4 = 0
        """ LCM Type: int16_t """

    def encode(self):
        buf = BytesIO()
        buf.write(sdk_lcmt_joint_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhhfhfhfffhhhh", self.component_type, self.joint_id, self.stat, self.pos_high, self.num_cycles_high, self.pos_low, self.num_cycles_low, self.vel, self.cur, self.tor, self.res1, self.res2, self.res3, self.res4))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sdk_lcmt_joint_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sdk_lcmt_joint_data._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sdk_lcmt_joint_data()
        self.component_type, self.joint_id, self.stat, self.pos_high, self.num_cycles_high, self.pos_low, self.num_cycles_low, self.vel, self.cur, self.tor, self.res1, self.res2, self.res3, self.res4 = struct.unpack(">hhhfhfhfffhhhh", buf.read(38))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sdk_lcmt_joint_data in parents: return 0
        tmphash = (0x6acb8601a0b1c5bb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sdk_lcmt_joint_data._packed_fingerprint is None:
            sdk_lcmt_joint_data._packed_fingerprint = struct.pack(">Q", sdk_lcmt_joint_data._get_hash_recursive([]))
        return sdk_lcmt_joint_data._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sdk_lcmt_joint_data._get_packed_fingerprint())[0]

