"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class system_load_t(object):

    __slots__ = ["timestamp", "cpu", "mem", "disk", "all_cpu"]

    __typenames__ = ["int64_t", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, [8]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.cpu = 0.0
        """ LCM Type: float """
        self.mem = 0.0
        """ LCM Type: float """
        self.disk = 0.0
        """ LCM Type: float """
        self.all_cpu = [ 0.0 for dim0 in range(8) ]
        """ LCM Type: float[8] """

    def encode(self):
        buf = BytesIO()
        buf.write(system_load_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.timestamp, self.cpu, self.mem, self.disk))
        buf.write(struct.pack('>8f', *self.all_cpu[:8]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != system_load_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return system_load_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = system_load_t()
        self.timestamp, self.cpu, self.mem, self.disk = struct.unpack(">qfff", buf.read(20))
        self.all_cpu = struct.unpack('>8f', buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if system_load_t in parents: return 0
        tmphash = (0x1f418ef292867a3c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if system_load_t._packed_fingerprint is None:
            system_load_t._packed_fingerprint = struct.pack(">Q", system_load_t._get_hash_recursive([]))
        return system_load_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", system_load_t._get_packed_fingerprint())[0]

