"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class teleop_arms_lcmt(object):

    __slots__ = ["ctrlWord", "tarPos", "kp", "kd"]

    __typenames__ = ["int16_t", "float", "float", "float"]

    __dimensions__ = [[12], [12], [12], [12]]

    def __init__(self):
        self.ctrlWord = [ 0 for dim0 in range(12) ]
        """ LCM Type: int16_t[12] """
        self.tarPos = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.kp = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.kd = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(teleop_arms_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12h', *self.ctrlWord[:12]))
        buf.write(struct.pack('>12f', *self.tarPos[:12]))
        buf.write(struct.pack('>12f', *self.kp[:12]))
        buf.write(struct.pack('>12f', *self.kd[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != teleop_arms_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return teleop_arms_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = teleop_arms_lcmt()
        self.ctrlWord = struct.unpack('>12h', buf.read(24))
        self.tarPos = struct.unpack('>12f', buf.read(48))
        self.kp = struct.unpack('>12f', buf.read(48))
        self.kd = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if teleop_arms_lcmt in parents: return 0
        tmphash = (0xbfca265778736238) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if teleop_arms_lcmt._packed_fingerprint is None:
            teleop_arms_lcmt._packed_fingerprint = struct.pack(">Q", teleop_arms_lcmt._get_hash_recursive([]))
        return teleop_arms_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", teleop_arms_lcmt._get_packed_fingerprint())[0]

