"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class testing_tools_package(object):

    __slots__ = ["timestamp", "command", "message"]

    __typenames__ = ["int64_t", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.command = ""
        """ LCM Type: string """
        self.message = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(testing_tools_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __command_encoded = self.command.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_encoded)+1))
        buf.write(__command_encoded)
        buf.write(b"\0")
        __message_encoded = self.message.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_encoded)+1))
        buf.write(__message_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != testing_tools_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return testing_tools_package._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = testing_tools_package()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __command_len = struct.unpack('>I', buf.read(4))[0]
        self.command = buf.read(__command_len)[:-1].decode('utf-8', 'replace')
        __message_len = struct.unpack('>I', buf.read(4))[0]
        self.message = buf.read(__message_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if testing_tools_package in parents: return 0
        tmphash = (0x2dae1f15f4aea7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if testing_tools_package._packed_fingerprint is None:
            testing_tools_package._packed_fingerprint = struct.pack(">Q", testing_tools_package._get_hash_recursive([]))
        return testing_tools_package._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", testing_tools_package._get_packed_fingerprint())[0]

