"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class upper_body_cmd_package(object):

    __slots__ = ["isUsed", "control_mode", "jointPosVec", "jointSpeedVec", "jointCurrentVec", "body_yaw"]

    __typenames__ = ["int32_t", "int32_t", "float", "float", "float", "float"]

    __dimensions__ = [None, [28], [28], [28], [28], None]

    def __init__(self):
        self.isUsed = 0
        """ LCM Type: int32_t """
        self.control_mode = [ 0 for dim0 in range(28) ]
        """ LCM Type: int32_t[28] """
        self.jointPosVec = [ 0.0 for dim0 in range(28) ]
        """
        control mode for fsm control
        LCM Type: float[28]
        """

        self.jointSpeedVec = [ 0.0 for dim0 in range(28) ]
        """
        -- joint pos     (14 left right actuators + 12  left right finger + 2 waist yaw roll )
        LCM Type: float[28]
        """

        self.jointCurrentVec = [ 0.0 for dim0 in range(28) ]
        """
        -- joint speed   (14 left right actuators + 12  left right finger + 2 waist yaw roll )
        LCM Type: float[28]
        """

        self.body_yaw = 0.0
        """
        -- joint current/force max value (14 left right actuators + 12  left right finger + 2 waist yaw roll)
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(upper_body_cmd_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.isUsed))
        buf.write(struct.pack('>28i', *self.control_mode[:28]))
        buf.write(struct.pack('>28f', *self.jointPosVec[:28]))
        buf.write(struct.pack('>28f', *self.jointSpeedVec[:28]))
        buf.write(struct.pack('>28f', *self.jointCurrentVec[:28]))
        buf.write(struct.pack(">f", self.body_yaw))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != upper_body_cmd_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return upper_body_cmd_package._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = upper_body_cmd_package()
        self.isUsed = struct.unpack(">i", buf.read(4))[0]
        self.control_mode = struct.unpack('>28i', buf.read(112))
        self.jointPosVec = struct.unpack('>28f', buf.read(112))
        self.jointSpeedVec = struct.unpack('>28f', buf.read(112))
        self.jointCurrentVec = struct.unpack('>28f', buf.read(112))
        self.body_yaw = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if upper_body_cmd_package in parents: return 0
        tmphash = (0x986309b48c31913a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if upper_body_cmd_package._packed_fingerprint is None:
            upper_body_cmd_package._packed_fingerprint = struct.pack(">Q", upper_body_cmd_package._get_hash_recursive([]))
        return upper_body_cmd_package._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", upper_body_cmd_package._get_packed_fingerprint())[0]

