"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class upper_body_data_package(object):

    __slots__ = ["isUsed", "curStatusVec", "curErrCodeVec", "curJointPosVec", "curSpeedVec", "curCurrentVec", "curTorqueVec", "endEffectorXYZRPY", "estimated_yaw"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, [28], [28], [28], [28], [28], [28], [24], None]

    def __init__(self):
        self.isUsed = 0
        """ LCM Type: int32_t """
        self.curStatusVec = [ 0 for dim0 in range(28) ]
        """
        current joint used status     (1 actuators)
        LCM Type: int32_t[28]
        """

        self.curErrCodeVec = [ 0 for dim0 in range(28) ]
        """
        current run mode              (14 actuators + 12 finger + 2 waist)
        LCM Type: int32_t[28]
        """

        self.curJointPosVec = [ 0.0 for dim0 in range(28) ]
        """
        current joint error code      (14 actuators + 12 finger + 2 waist)
        LCM Type: float[28]
        """

        self.curSpeedVec = [ 0.0 for dim0 in range(28) ]
        """
        current joint pos             (14 actuators + 12 finger + 2 waist)
        LCM Type: float[28]
        """

        self.curCurrentVec = [ 0.0 for dim0 in range(28) ]
        """
        current joint speed           (14 actuators + 12 finger + 2 waist)
        LCM Type: float[28]
        """

        self.curTorqueVec = [ 0.0 for dim0 in range(28) ]
        """
        current joint current/figure force  (14 actuators + 12 finger + 2 waist)
        LCM Type: float[28]
        """

        self.endEffectorXYZRPY = [ 0.0 for dim0 in range(24) ]
        """
        current joint torque          (14 actuators + 12 finger + 2 waist)
        LCM Type: float[24]
        """

        self.estimated_yaw = 0.0
        """
        real left arm xyzrpy / right arm xyzrpy + cmd left arm xyzrpy / right arm xyzrpy
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(upper_body_data_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.isUsed))
        buf.write(struct.pack('>28i', *self.curStatusVec[:28]))
        buf.write(struct.pack('>28i', *self.curErrCodeVec[:28]))
        buf.write(struct.pack('>28f', *self.curJointPosVec[:28]))
        buf.write(struct.pack('>28f', *self.curSpeedVec[:28]))
        buf.write(struct.pack('>28f', *self.curCurrentVec[:28]))
        buf.write(struct.pack('>28f', *self.curTorqueVec[:28]))
        buf.write(struct.pack('>24f', *self.endEffectorXYZRPY[:24]))
        buf.write(struct.pack(">f", self.estimated_yaw))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != upper_body_data_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return upper_body_data_package._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = upper_body_data_package()
        self.isUsed = struct.unpack(">i", buf.read(4))[0]
        self.curStatusVec = struct.unpack('>28i', buf.read(112))
        self.curErrCodeVec = struct.unpack('>28i', buf.read(112))
        self.curJointPosVec = struct.unpack('>28f', buf.read(112))
        self.curSpeedVec = struct.unpack('>28f', buf.read(112))
        self.curCurrentVec = struct.unpack('>28f', buf.read(112))
        self.curTorqueVec = struct.unpack('>28f', buf.read(112))
        self.endEffectorXYZRPY = struct.unpack('>24f', buf.read(96))
        self.estimated_yaw = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if upper_body_data_package in parents: return 0
        tmphash = (0x7353a8fd01366e92) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if upper_body_data_package._packed_fingerprint is None:
            upper_body_data_package._packed_fingerprint = struct.pack(">Q", upper_body_data_package._get_hash_recursive([]))
        return upper_body_data_package._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", upper_body_data_package._get_packed_fingerprint())[0]

