"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class vacumm_io_cmd(object):

    __slots__ = ["power_on"]

    __typenames__ = ["int32_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.power_on = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(vacumm_io_cmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.power_on))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != vacumm_io_cmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vacumm_io_cmd._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = vacumm_io_cmd()
        self.power_on = struct.unpack(">i", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if vacumm_io_cmd in parents: return 0
        tmphash = (0xb7a2877be5e18ed0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if vacumm_io_cmd._packed_fingerprint is None:
            vacumm_io_cmd._packed_fingerprint = struct.pack(">Q", vacumm_io_cmd._get_hash_recursive([]))
        return vacumm_io_cmd._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", vacumm_io_cmd._get_packed_fingerprint())[0]

