"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class wearable_data_lcmt(object):

    __slots__ = ["ref_qpos_"]

    __typenames__ = ["float"]

    __dimensions__ = [[28]]

    def __init__(self):
        self.ref_qpos_ = [ 0.0 for dim0 in range(28) ]
        """ LCM Type: float[28] """

    def encode(self):
        buf = BytesIO()
        buf.write(wearable_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>28f', *self.ref_qpos_[:28]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != wearable_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return wearable_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = wearable_data_lcmt()
        self.ref_qpos_ = struct.unpack('>28f', buf.read(112))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if wearable_data_lcmt in parents: return 0
        tmphash = (0xb9d8cc0d87a23550) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if wearable_data_lcmt._packed_fingerprint is None:
            wearable_data_lcmt._packed_fingerprint = struct.pack(">Q", wearable_data_lcmt._get_hash_recursive([]))
        return wearable_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", wearable_data_lcmt._get_packed_fingerprint())[0]

